apiVersion: v1
kind: ConfigMap
metadata:
  name: dagent-config
data:
  APP_NAME: dagent
  DEBUG: "false"
  AUTO_CREATE_SCHEMA: "true"
  SEED_DEMO_DATA: "true"
  QUICK_LOGIN_ENABLED: "true"
  CORS_ORIGINS: "http://127.0.0.1:5173,http://localhost:5173,https://bold-spine-leon-bids.trycloudflare.com"
  AGENT_RUNTIME_ENABLED: "true"
  REQUIREMENT_RUNTIME_ENABLED: "true"
  REQUIREMENT_RUNTIME_NAMESPACE: "dagent"
  REQUIREMENT_CLARIFICATION_IMAGE: "registry.cn-hangzhou.aliyuncs.com/citics_lwj/dagent:requirement-clarification-v1.0.0"
  DEVELOPMENT_DOCUMENT_IMAGE: "registry.cn-hangzhou.aliyuncs.com/citics_lwj/dagent:development-document-v1.0.0"
  DEVELOPMENT_AGENT_IMAGE: "registry.cn-hangzhou.aliyuncs.com/citics_lwj/dagent:development-v1.0.0"
  WORKSPACE_MANAGER_IMAGE: "registry.cn-hangzhou.aliyuncs.com/citics_lwj/dagent:workspace-manager-v1.0.0"
  REQUIREMENT_RUNTIME_IMAGE_PULL_SECRET: "opencode-pull-secret"
  REQUIREMENT_RUNTIME_STORAGE_CLASS: "alicloud-disk-topology-alltype"
  REQUIREMENT_RUNTIME_STORAGE_SIZE: "20Gi"
  REQUIREMENT_RUNTIME_RECONCILE_SECONDS: "15"
  REQUIREMENT_RUNTIME_SERVICE_TEMPLATE: "http://dagent-requirement-{requirement_id}"
  WORKSPACE_MANAGER_URL: "http://dagent-repository-verifier:8090"
  AGENT_INTERNAL_API_URL: "http://127.0.0.1:8000/api/v1"
  AGENT_WORKSPACE_ROOT: "/workspaces"
