apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dagent
resources:
  - namespace.yaml
  - configmap.yaml
  - mysql-rds.yaml
  - requirement-runtime-rbac.yaml
  - requirement-runtime-network-policy.yaml
  - repository-verifier.yaml
  - backend.yaml
  - frontend.yaml
  - frontend-tunnel.yaml
images:
  - name: dagent-backend
    newName: registry.cn-hangzhou.aliyuncs.com/citics_lwj/dagent
    newTag: backend-v1.0.0
  - name: dagent-web
    newName: registry.cn-hangzhou.aliyuncs.com/citics_lwj/dagent
    newTag: web-v1.0.0
  - name: dagent-workspace-manager
    newName: registry.cn-hangzhou.aliyuncs.com/citics_lwj/dagent
    newTag: workspace-manager-v1.0.0
  - name: dagent-cloudflared
    newName: registry.cn-hangzhou.aliyuncs.com/citics_lwj/dagent
    newTag: cloudflared-e39ee8da81ad
